-- 1. Create the database if it's missing
CREATE DATABASE IF NOT EXISTS acebank;
USE acebank;

-- 2. Enhanced USERS (Focus on Identity)
CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AADHAAR_NO VARCHAR(12) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Separate ACCOUNTS (A user can have multiple)
CREATE TABLE ACCOUNTS (
    ACCOUNT_NO INT PRIMARY KEY,
    USER_ID INT,
    ACCOUNT_TYPE ENUM('SAVINGS', 'CHECKING', 'LOAN') DEFAULT 'SAVINGS',
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS ENUM('ACTIVE', 'BLOCKED', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 4. Refined TRANSACTIONS
CREATE TABLE TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ACCOUNT INT,
    RECEIVER_ACCOUNT INT,
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TX_TYPE ENUM('TRANSFER', 'DEPOSIT', 'WITHDRAWAL') NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO)
);