-- CREATE DATABASE IF NOT EXISTS acebank;
-- USE acebank;

-- Tables (IF NOT EXISTS)
CREATE TABLE IF NOT EXISTS USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AADHAAR_NO VARCHAR(12) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ACCOUNTS (
    ACCOUNT_NO INT PRIMARY KEY,
    USER_ID INT,
    ACCOUNT_TYPE ENUM('SAVINGS', 'CHECKING', 'LOAN') DEFAULT 'SAVINGS',
    BALANCE DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    STATUS ENUM('ACTIVE', 'BLOCKED', 'CLOSED') DEFAULT 'ACTIVE',
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    SENDER_ACCOUNT INT NULL,   -- NULL for Deposits
    RECEIVER_ACCOUNT INT NULL, -- NULL for Withdrawals
    AMOUNT DECIMAL(15, 2) NOT NULL,
    TX_TYPE ENUM('TRANSFER', 'DEPOSIT', 'WITHDRAWAL') NOT NULL,
    REMARK VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SENDER_ACCOUNT) REFERENCES ACCOUNTS(ACCOUNT_NO)
    );

-- Idempotent Dummy Data
INSERT IGNORE INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, AADHAAR_NO, EMAIL, PASSWORD_HASH)
VALUES (1, 'John', 'Doe', '123456789012', 'john@example.com', 'hashed_pw_1'),
       (2, 'Jane', 'Doe', '123456789013', 'jane@example.com', 'hashed_pw_2');

INSERT IGNORE INTO ACCOUNTS (ACCOUNT_NO, USER_ID, ACCOUNT_TYPE, BALANCE)
VALUES (1001, 1, 'SAVINGS', 5000.00),
       (1002, 2, 'CHECKING', 2500.00);

-- Insert transaction only if it hasn't been recorded yet
INSERT INTO TRANSACTIONS (SENDER_ACCOUNT, RECEIVER_ACCOUNT, AMOUNT, TX_TYPE, REMARK)
SELECT 1001, 1002, 500.00, 'TRANSFER', 'Rent'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRANSACTIONS WHERE SENDER_ACCOUNT = 1001 AND AMOUNT = 500.00);