package dev.codecounty.acebank.controllers;

import dev.codecounty.acebank.model.LoginResult;
import dev.codecounty.acebank.model.User;
import dev.codecounty.acebank.service.BankService;
import dev.codecounty.acebank.service.BankServiceImpl;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import lombok.extern.java.Log;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Optional;

@Log
@WebServlet("/SignUp")
public class SignUp extends HttpServlet {
    private static final long serialVersionUID = 1L;

    // Use the service, not the DAO directly
    private final BankService bankService = new BankServiceImpl();

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        // 1. Extract Data
        String firstName = request.getParameter("firstName");
        String lastName = request.getParameter("lastName");
        String aadharStr = request.getParameter("aadharNumber");
        String email = request.getParameter("email");
        String password = request.getParameter("password");

        try {
            // 2. Create the immutable Record
            User newUser = new User(
                    null, // ID generated by DB
                    firstName,
                    lastName,
                    aadharStr,
                    email,
                    password, // Note: Should be hashed in the Service layer
                    null  // CreatedAt generated by DB
            );

            // 3. Call Service to handle logic
            Optional<LoginResult> resultOpt = bankService.registerUser(newUser);

            if (resultOpt.isPresent()) {
                var details = resultOpt.get();
                HttpSession session = request.getSession();

                // 4. Set Session Attributes
                session.setAttribute("firstName", details.firstName());
                session.setAttribute("email", details.email());
                session.setAttribute("balance", details.balance());
                session.setAttribute("transactionDetailsList", new ArrayList<>());

                response.sendRedirect("Home.jsp");
            } else {
                response.sendRedirect("GenericError.html");
            }

        } catch (Exception e) {
            log.severe("SignUp Servlet Error: " + e.getMessage());
            response.sendRedirect("GenericError.html");
        }
    }
}